trigger: none

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.21'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
                
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Dmaven.clean.skip=true'
          goals: 'verify'
          publishJUnitResults: false
          codeCoverageToolOption: 'JaCoCo'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.21'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

      #- task: PublishCodeCoverageResults@2
      #  inputs:
      #    summaryFileLocation: 'code-coverage/target/site/jacoco-aggregate/jacoco.xml'
      #    pathToSources: 'src/main/java/com/training/example/JacocoExample'