trigger: none

jobs:
  - job: Build1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      #- task: Maven@4
      #  inputs:
      #    mavenPomFile: 'pom.xml'
      #    goals: 'clean package'
      #    publishJUnitResults: true
      #    testResultsFiles: '**/surefire-reports/TEST-*.xml'
      #    javaHomeOption: 'JDKVersion'
      #    jdkVersionOption: '1.21'
      #    mavenVersionOption: 'Default'
      #    mavenOptions: '-Xmx3072m'
      #    mavenAuthenticateFeed: false
      #    effectivePomSkip: false
      #    sonarQubeRunAnalysis: false
                
#      - task: Maven@4
#        inputs:
#          mavenPomFile: 'pom.xml'
#          options: '-Dmaven.clean.skip=true -DdummyParam1=dummyValue1 -DdummyParam2=dummyValue2'
#          goals: 'verify'
#          publishJUnitResults: true
#          codeCoverageToolOption: 'JaCoCo'
#          javaHomeOption: 'JDKVersion'
#          jdkVersionOption: '1.21'
#          mavenVersionOption: 'Default'
#          mavenOptions: '-Xmx3072m'
#          mavenAuthenticateFeed: false
#          effectivePomSkip: false
#          sonarQubeRunAnalysis: false

      #- task: PublishCodeCoverageResults@2
      #  inputs:
      #    summaryFileLocation: 'code-coverage/target/site/jacoco-aggregate/jacoco.xml'
      #    pathToSources: 'src/main/java/com/training/example/JacocoExample'
      - task: PowerShell@2
        name: SetVar
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            $dirs = Get-ChildItem -Path "."
            $param = @()
            
            foreach ($dir in $dirs) {
              Write-Host $dir.FullName
              $param += @{
                FullName=$dir.FullName
                BaseName=$dir.BaseName
              }    
            }

            Write-Host $param
            $paramJson = ConvertTo-Json $param -Compress
            Write-Host "##vso[task.setvariable variable=MY_PARAM;isOutput=true]$paramJson"
    
  - job: Build2
    dependsOn: Build1
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - name: myParam
        value: $[ dependencies.Build1.outputs['SetVar.MY_PARAM'] ]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Get-ChildItem Env:
            $dirs = Get-ChildItem -Path "."
            
            foreach ($dir in $dirs) {
              Write-Host $dir.FullName
            }

            $x = $Env:MY_PARAM
            Write-Host $x
